### ISSUE TITLE
tip table: compliment_count has discrepency

### ISSUE THREAD

**Issue by mohsenualam** [CIS-4560-Team-2/Hive-on-Yelp#4]

**Comment by mohsenualam** [comment]
```select count(*) from raw_tip where get_json_object(json_response, '$.compliment_count') = 0;```  yields **1302089**. However, ``` select count(*) from tip where compliment_count = 0; ``` yields **1275223**.

Some raw_tip records' compliment_count didn't parse correctly.

**Comment by LunettoRandall** [comment]
It appears the 'tip' table has 54,816 more records total than the 'raw_tip' table.

`select count(*) from raw_tip where get_json_object(json_response, '$.compliment_count') IS NULL;` 
yields **0**
`select count(*) from raw_tip where get_json_object(json_response, '$.compliment_count') IS NOT NULL;`
yields **1,320,761**

--
`select count(*) from tip where tip_compliment_count IS  NULL;`
yields **82,384**
`select count(*) from tip where tip_compliment_count IS NOT NULL;`
yields **1,293,193**

If there are more records total in the 'cleaned' table, this may imply another delimiters issue? 
Some kind of separator character adding more records?

**Comment by mohsenualam** [comment]
> It appears the 'tip' table has 54,816 more records total than the 'raw_tip' table.
> 
> `select count(*) from raw_tip where get_json_object(json_response, '$.compliment_count') IS NULL;`
> yields **0**
> `select count(*) from raw_tip where get_json_object(json_response, '$.compliment_count') IS NOT NULL;`
> yields **1,320,761**
> 
> --
> `select count(*) from tip where tip_compliment_count IS NULL;`
> yields **82,384**
> `select count(*) from tip where tip_compliment_count IS NOT NULL;`
> yields **1,293,193**
> 
> If there are more records total in the 'cleaned' table, this may imply another delimiters issue?
> Some kind of separator character adding more records?

Thanks for the heads up! Yeah, it is a delimiter or separator issue.  When I ran ```select * from tip where tip_compliment_count is null limit 5;```, I see some empty rows with null values. 
One of the text attribute: "It's my first hair salon in America. \nI like it so much.\nThank you Stella." I am fixing the issue by using a regexp_replace for \n characters.

**Comment by mohsenualam** [comment]
Updated in [this commit](https://github.com/CIS-4560-Team-2/Hive-on-Yelp/commit/0fb235992ee407725fe79a52cd622af25cc77540) 
Thanks @LunettoRandall !
